//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoVan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incoming_Shipment_Detail
    {
        public int Detail_ID { get; set; }
        public Nullable<int> Shipment_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual Incoming_Shipments Incoming_Shipments { get; set; }
    }
}
