//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoVan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        public int Shipment_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string status { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Order Order { get; set; }
    }
}
